### ISSUE TITLE
Powering off via BLE

### ISSUE THREAD

**Issue by niru-27** [KonradIT/gopro-ble-py#1]
Hi,

First of all, great work with all the GoPro hacks. Keep it up! :)

I tried out some of the BLE stuff on a Hero6. The byte array **b'\x01\x04'** seems to crash the H6-it switches off before completing the beep sequence, and cannot be woken via BLE.

I tried **b'\x01\x05'** and it seems to perform a "graceful shutdown".

Was wondering if it's the same with H5 as well.

Cheers

**Comment by KonradIT** [comment]
It works on the 5. Byte 5 is the equivalent of /sleep. Can you submit a PR?

**Comment by niru-27** [comment]
On further testing, I observed the following:
**Byte 4** : Complete shutdown of the camera; WiFi and BLE are turned off. Wireless wake not possible
**Byte 5** : Sleep. Wifi stays on for about 10 mins after camera powers off, BLE for (at least) a couple of hours). Could turn the camera on via BLE

**Comment by KonradIT** [comment]
Pushed to 89c582b
