### ISSUE TITLE
Change Settings

### ISSUE THREAD

**Issue by shubham9436** [KonradIT/gopro-ble-py#15]
Hi,

Just like GoPro WiFi commands, could you please enlist all the bytearray for each settings.
For example, for turning on Wifi, we use `bytearray(b'\x03\x17\x01\x01')` .

Though I need specifically for:
1. Turning On GPS
2. Auto Off
3. Photo Lens
4. Photo Timer
5. Photo Zoom
6. Shutter
7. White Balance
8. ISO Min, ISO Max
9. Sharpness
10. Color

**Comment by KonradIT** [comment]
Please look at how I did it in the code: https://github.com/KonradIT/gopro-ble-py/blob/v2/main.py#L151

I use the wifi commands for BLE as well.
