### ISSUE TITLE
Wifi and Bluetooth using together

### ISSUE THREAD

**Issue by alexleandrom** [KonradIT/gopro-ble-py#6]
Hi KonradIT, first, thanks for this great job in gopro library. I started using only wifihack, but today I am using the python lib for control a list of gopro. I created a small REST API to control a raspberry which is connected to a gopro. I have only one problem, time to download files. I am trying to record a video and download last media to my raspberry, but when downloading is running I can start a new record. My question is: Can I use Record and Stop from bluetooth and Wifi just for download? Is it possible using this 2 features in parallel?

**Comment by KonradIT** [comment]
Hi, yes. Just make sure to download when the camera is idle.
