### ISSUE TITLE
Switching between standard and 360 capture

### ISSUE THREAD

**Issue by KevinJosephMorin** [KonradIT/gopro-ble-py#8]
Do you know what the BT command for switching between a single lens and the 360/dual lens is?

https://github.com/KonradIT/gopro-ble-py/blob/v2/commands.py

Kevin

**Comment by KevinJosephMorin** [comment]
I was able to figure this out by studying the BT packets.  For anyone else interested, here is the command to toggle between one lens and two lens.  I tested this on the GoPro Max only.

b5f900**74**-aa8d-11e3-9046-0002a5d5c51b

Dual lens (360): 0x03 0x8e 0x01 0x01

Single lens: 0x03 0x8e 0x01 0x00

**Comment by KonradIT** [comment]
Hi, yes, you can change the settings using the integers I defined in my python API, for example: [142 == 0x8e for Lens Mode](https://github.com/KonradIT/gopro-py-api/blob/master/goprocam/constants.py#L638).

Hope you found this lib helpful
